"use client";
import {ChangeEvent,DragEvent,useCallback,useMemo,useRef,useState} from "react";
type State="ready"|"uploading"|"done"|"error";
type Item={id:string;file:File;state:State;progress:number;error?:string;blob?:Blob;outputName?:string};
const accepted=["pdf","docx","doc","xlsx","xls","csv","epub","mobi","png","jpg","jpeg","tif","tiff","djvu","zip","tar","tgz"];
const api=(process.env.NEXT_PUBLIC_MDFY_API_URL||"/api").replace(/\/$/,"");
const ext=(n:string)=>n.toLowerCase().split(".").pop()||"";
const size=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
export default function Home(){
 const input=useRef<HTMLInputElement>(null);const[items,setItems]=useState<Item[]>([]);const[drag,setDrag]=useState(false);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 const add=useCallback((files:File[])=>{const valid:Item[]=[];const bad:string[]=[];files.forEach(file=>{if(!accepted.includes(ext(file.name)))bad.push(file.name);else if(file.size>100*1024*1024)bad.push(`${file.name} (>100 MB)`);else valid.push({id:`${file.name}-${file.size}-${file.lastModified}`,file,state:"ready",progress:0})});setItems(old=>[...old,...valid.filter(n=>!old.some(o=>o.id===n.id))]);setNotice(bad.length?`Não foi possível adicionar: ${bad.join(", ")}.`:"")},[]);
 const choose=(e:ChangeEvent<HTMLInputElement>)=>{add(Array.from(e.target.files||[]));e.target.value=""};
 const drop=(e:DragEvent<HTMLDivElement>)=>{e.preventDefault();setDrag(false);add(Array.from(e.dataTransfer.files))};
 const convert=async()=>{setBusy(true);setNotice("");for(const item of items.filter(x=>x.state==="ready"||x.state==="error")){setItems(a=>a.map(x=>x.id===item.id?{...x,state:"uploading",progress:25,error:undefined}:x));try{const body=new FormData();body.append("file",item.file);const r=await fetch(`${api}/convert`,{method:"POST",body});if(!r.ok)throw new Error((await r.text())||"Serviço indisponível");setItems(a=>a.map(x=>x.id===item.id?{...x,progress:75}:x));const blob=await r.blob();const outputName=r.headers.get("x-output-filename")||`${item.file.name.replace(/\.[^.]+$/,"")}.md`;setItems(a=>a.map(x=>x.id===item.id?{...x,state:"done",progress:100,blob,outputName}:x))}catch(e){setItems(a=>a.map(x=>x.id===item.id?{...x,state:"error",progress:0,error:e instanceof Error?e.message:"Falha inesperada"}:x))}}setBusy(false)};
 const download=(item:Item)=>{if(!item.blob)return;const a=document.createElement("a");a.href=URL.createObjectURL(item.blob);a.download=item.outputName||"arquivo.md";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 const done=useMemo(()=>items.filter(x=>x.state==="done").length,[items]);
 return <main><header className="topbar"><a className="brand" href="#inicio"><span className="brandMark">M↓</span><span>MDfy</span></a><nav><a href="#formatos">Formatos</a><a href="#como-funciona">Como funciona</a><a href="#privacidade">Privacidade</a></nav><a className="githubLink" href="https://github.com/fdossi/MDfy" target="_blank" rel="noreferrer">GitHub ↗</a></header>
 <section className="hero" id="inicio"><div className="eyebrow"><i/> Conversão simples, rápida e segura</div><h1>Seus arquivos, agora em <em>Markdown.</em></h1><p className="heroText">Converta documentos, planilhas, e-books e imagens em arquivos <code>.md</code> limpos — individualmente ou em lote.</p>
 <div className="converterCard"><div className={`dropZone ${drag?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop} onClick={()=>input.current?.click()} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")input.current?.click()}}><input ref={input} type="file" multiple accept={accepted.map(x=>`.${x}`).join(",")} onChange={choose} hidden/><div className="uploadIcon">↑</div><h2>Arraste seus arquivos para cá</h2><p>ou <button type="button" onClick={e=>{e.stopPropagation();input.current?.click()}}>selecione no seu dispositivo</button></p><span>Até 100 MB por arquivo · vários arquivos de uma vez</span></div>
 {notice&&<div className="notice" role="alert">{notice}</div>}{items.length>0&&<div className="fileList"><div className="listHeader"><strong>{items.length} {items.length===1?"arquivo":"arquivos"}</strong><button onClick={()=>setItems([])} disabled={busy}>Limpar lista</button></div>{items.map(item=><article className="fileRow" key={item.id}><div className="fileBadge">{ext(item.file.name).slice(0,4).toUpperCase()}</div><div className="fileMeta"><strong>{item.file.name}</strong><span>{size(item.file.size)} · {item.state==="ready"?"Pronto para converter":item.state==="uploading"?"Convertendo…":item.state==="done"?"Conversão concluída":item.error}</span>{item.state==="uploading"&&<div className="progress"><i style={{width:`${item.progress}%`}}/></div>}</div>{item.state==="done"?<button className="downloadBtn" onClick={()=>download(item)}>Baixar .MD</button>:<button className="removeBtn" aria-label={`Remover ${item.file.name}`} onClick={()=>setItems(a=>a.filter(x=>x.id!==item.id))} disabled={busy}>×</button>}</article>)}<button className="convertButton" onClick={convert} disabled={busy||done===items.length}>{busy?"Convertendo arquivos…":done?"Converter restantes":"Converter para Markdown"}</button></div>}</div><p className="trust"><span>✓</span> Processamento temporário <span>✓</span> Sem cadastro <span>✓</span> Download imediato</p></section>
 <section className="formats section" id="formatos"><Intro over="FORMATOS COMPATÍVEIS" title="Um conversor para o seu fluxo inteiro." text="Do relatório científico à planilha de dados, sem copiar e colar."/><div className="formatGrid">{[["Documentos","PDF · DOCX · DOC","▤"],["Planilhas","XLSX · XLS · CSV","▦"],["E-books","EPUB · MOBI","▥"],["Imagens","PNG · JPG · TIFF","▧"],["Digitalizados","DJVU","◫"],["Pacotes","ZIP · TAR · TGZ","◇"]].map(x=><article key={x[0]}><b>{x[2]}</b><div><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div></section>
 <section className="steps section" id="como-funciona"><Intro over="COMO FUNCIONA" title="Do arquivo ao Markdown em três passos."/><div className="stepGrid">{[["01","Envie","Selecione um ou vários arquivos compatíveis."],["02","Converta","O conteúdo e a estrutura são extraídos automaticamente."],["03","Baixe","Receba cada .md ou um pacote organizado."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <section className="privacy section" id="privacidade"><div><span>PRIVACIDADE POR PADRÃO</span><h2>Seus documentos não viram nossos dados.</h2><p>Os arquivos são usados somente durante a conversão e excluídos automaticamente depois que o resultado é entregue. Não exigimos conta e não usamos o conteúdo para treinamento.</p></div><div className="shield">✓</div></section><footer><a className="brand" href="#inicio"><span className="brandMark">M↓</span><span>MDfy</span></a><p>Conversão de arquivos para Markdown, sem complicação.</p><span>Projeto de código aberto · 2026</span></footer></main>}
function Intro({over,title,text}:{over:string;title:string;text?:string}){return <div className="sectionIntro"><span>{over}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
