"use client";
import {ChangeEvent,DragEvent,useCallback,useMemo,useRef,useState} from "react";
import JSZip from "jszip";
import {convertLocally,LOCAL_FORMATS} from "./local-converter";
type State="ready"|"converting"|"advanced"|"done"|"error";
type Item={id:string;file:File;state:State;progress:number;error?:string;blob?:Blob;outputName?:string};
const accepted=["pdf","docx","doc","xlsx","xls","csv","epub","mobi","png","jpg","jpeg","tif","tiff","djvu","zip","tar","tgz"];
const colabUrl=process.env.NEXT_PUBLIC_MDFY_COLAB_URL||"https://colab.research.google.com/github/fdossi/mdfy-runtime/blob/main/colab/MDfy_Colab.ipynb";
const maxLocalSize=100*1024*1024;
const ext=(name:string)=>name.toLowerCase().split(".").pop()||"";
const size=(value:number)=>value<1024?`${value} B`:value<1048576?`${(value/1024).toFixed(1)} KB`:`${(value/1048576).toFixed(1)} MB`;
export default function Home(){
 const input=useRef<HTMLInputElement>(null);const[items,setItems]=useState<Item[]>([]);const[drag,setDrag]=useState(false);const[busy,setBusy]=useState(false);const[zipping,setZipping]=useState(false);const[notice,setNotice]=useState("");
 const add=useCallback((files:File[])=>{const valid:Item[]=[];const bad:string[]=[];files.forEach(file=>{if(!accepted.includes(ext(file.name)))bad.push(file.name);else{const useColab=file.size>maxLocalSize;valid.push({id:`${file.name}-${file.size}-${file.lastModified}`,file,state:useColab?"advanced":"ready",progress:0,error:useColab?"Arquivo acima de 100 MB: use o Google Colab.":undefined})}});setItems(old=>[...old,...valid.filter(next=>!old.some(current=>current.id===next.id))]);setNotice(bad.length?`Formato não compatível: ${bad.join(", ")}.`:"")},[]);
 const choose=(event:ChangeEvent<HTMLInputElement>)=>{add(Array.from(event.target.files||[]));event.target.value=""};
 const drop=(event:DragEvent<HTMLDivElement>)=>{event.preventDefault();setDrag(false);add(Array.from(event.dataTransfer.files))};
 const convert=async()=>{setBusy(true);setNotice("");for(const item of items.filter(value=>value.state==="ready"||value.state==="error")){if(!LOCAL_FORMATS.has(ext(item.file.name))){setItems(all=>all.map(value=>value.id===item.id?{...value,state:"advanced",progress:0,error:undefined}:value));continue}setItems(all=>all.map(value=>value.id===item.id?{...value,state:"converting",progress:35,error:undefined}:value));try{const blob=await convertLocally(item.file);setItems(all=>all.map(value=>value.id===item.id?{...value,state:"done",progress:100,blob,outputName:`${item.file.name.replace(/\.[^.]+$/,'')}.md`}:value))}catch(error){setItems(all=>all.map(value=>value.id===item.id?{...value,state:"advanced",progress:0,error:error instanceof Error?error.message:"Este arquivo requer o conversor avançado."}:value))}}setBusy(false)};
 const download=(item:Item)=>{if(!item.blob)return;const a=document.createElement("a");a.href=URL.createObjectURL(item.blob);a.download=item.outputName||"arquivo.md";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 const downloadAll=async()=>{const converted=items.filter((item):item is Item&{blob:Blob}=>item.state==="done"&&Boolean(item.blob));if(!converted.length)return;setZipping(true);setNotice("");try{const zip=new JSZip();const used=new Set<string>();const unique=(raw:string)=>{const safe=raw.replace(/^[/\\]+/,"").replace(/[<>:\"|?*]/g,"-")||"arquivo.md";if(!used.has(safe)){used.add(safe);return safe}const dot=safe.lastIndexOf(".");const stem=dot>0?safe.slice(0,dot):safe;const suffix=dot>0?safe.slice(dot):"";let n=2;while(used.has(`${stem}-${n}${suffix}`))n++;const name=`${stem}-${n}${suffix}`;used.add(name);return name};for(const item of converted)zip.file(unique(item.outputName||`${item.file.name.replace(/\.[^.]+$/,'')}.md`),item.blob);const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`mdfy-markdown-${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(error){setNotice(error instanceof Error?`Não foi possível criar o ZIP: ${error.message}`:"Não foi possível criar o ZIP.")}finally{setZipping(false)}};
 const completed=useMemo(()=>items.filter(x=>x.state==="done"),[items]);const pending=useMemo(()=>items.filter(x=>x.state!=="done"),[items]);const advanced=useMemo(()=>items.filter(x=>x.state==="advanced").length,[items]);const canConvert=items.some(x=>x.state==="ready"||x.state==="error");
 return <main><header className="topbar"><a className="brand" href="#inicio"><span className="brandMark">M↓</span><span>MDfy</span></a><nav><a href="#formatos">Formatos</a><a href="#recursos">Recursos</a><a href="#privacidade">Privacidade</a></nav><a className="githubLink" href={colabUrl} target="_blank" rel="noreferrer">Abrir no Colab ↗</a></header>
 <section className="hero" id="inicio"><span className="eyebrow">CONVERSOR GRATUITO E OPEN SOURCE</span><h1>Converta arquivos para Markdown</h1><p>Transforme documentos, planilhas e e-books em arquivos .md limpos, editáveis e prontos para GitHub, documentação e modelos de linguagem.</p>
 <div className="converterCard"><div className={`dropZone ${drag?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop} onClick={()=>input.current?.click()} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")input.current?.click()}}><input ref={input} type="file" multiple accept={accepted.map(x=>`.${x}`).join(",")} onChange={choose} hidden/><div className="fileIcon">≡</div><h2>Envie seus arquivos</h2><p>Arraste e solte aqui ou selecione no seu dispositivo</p><button className="chooseButton" type="button" onClick={e=>{e.stopPropagation();input.current?.click()}}>Selecionar arquivos</button><small>Vários arquivos · acima de 100 MB via Google Colab</small></div>
 {notice&&<div className="notice" role="alert">{notice}</div>}{items.length>0&&<div className="queue"><div className="queueHeader"><strong>{items.length} {items.length===1?"arquivo":"arquivos"}</strong><button onClick={()=>setItems([])} disabled={busy||zipping}>Limpar</button></div><div className="fileList">{pending.map(item=><article className="fileRow" key={item.id}><div className="typeBadge">{ext(item.file.name).slice(0,4).toUpperCase()}</div><div className="fileMeta"><strong>{item.file.name}</strong><span>{size(item.file.size)} · {item.state==="ready"?(LOCAL_FORMATS.has(ext(item.file.name))?"Pronto para converter":"Conversão avançada"):item.state==="converting"?"Convertendo…":item.state==="advanced"?(item.error||"Requer ambiente avançado"):item.error}</span>{item.state==="converting"&&<div className="progress"><i style={{width:`${item.progress}%`}}/></div>}</div><button className="removeBtn" onClick={()=>setItems(all=>all.filter(x=>x.id!==item.id))} disabled={busy} aria-label={`Remover ${item.file.name}`}>×</button></article>)}{completed.map(item=><article className="fileRow done" key={item.id}><div className="typeBadge">MD</div><div className="fileMeta"><strong>{item.outputName}</strong><span>{size(item.blob?.size||0)} · Concluído</span></div><button className="downloadBtn" onClick={()=>download(item)}>Baixar</button></article>)}</div><div className="actions">{canConvert&&<button className="convertButton" onClick={convert} disabled={busy}>{busy?"Convertendo…":"Converter para Markdown"}</button>}{completed.length>1&&<button className="zipButton" onClick={downloadAll} disabled={busy||zipping}>{zipping?"Criando ZIP…":`Baixar todos em ZIP (${completed.length})`}</button>}</div>{advanced>0&&<div className="advancedPanel"><div><strong>{advanced} {advanced===1?"arquivo requer":"arquivos requerem"} conversão avançada</strong><p>Abra o conversor no Google Colab para OCR, imagens, pacotes e formatos antigos.</p></div><div><a href={colabUrl} target="_blank" rel="noreferrer">Abrir no Colab ↗</a></div></div>}</div>}</div></section>
 <section className="features" id="recursos"><article><span>◎</span><h3>Conversão local</h3><p>PDF, DOCX, XLSX, CSV e EPUB são processados no navegador.</p></article><article><span>▦</span><h3>Estrutura preservada</h3><p>Títulos, listas, tabelas e links são mantidos quando possível.</p></article><article><span>↻</span><h3>Download em lote</h3><p>Baixe cada Markdown ou reúna todos em um único ZIP.</p></article></section>
 <section className="formats" id="formatos"><div><span>FORMATOS COMPATÍVEIS</span><h2>Um fluxo simples para diversos arquivos</h2><p>Conversão direta para os formatos mais comuns e ambiente avançado gratuito quando OCR ou ferramentas adicionais são necessários.</p></div><div className="formatTags">{accepted.map(x=><b key={x}>{x.toUpperCase()}</b>)}</div></section>
 <footer id="privacidade"><div><a className="brand" href="#inicio"><span className="brandMark">M↓</span><span>MDfy</span></a><p>Conversor aberto de arquivos para Markdown.</p></div><div><strong>Privacidade por padrão</strong><p>Arquivos compatíveis são processados localmente no navegador.</p></div><a href="https://github.com/fdossi/MDfy" target="_blank" rel="noreferrer">Ver código no GitHub ↗</a></footer></main>}
