"use client";
import {ChangeEvent,DragEvent,useCallback,useMemo,useRef,useState} from "react";
import JSZip from "jszip";
import {convertLocally,LOCAL_FORMATS} from "./local-converter";
type State="ready"|"converting"|"advanced"|"done"|"error";
type Item={id:string;file:File;state:State;progress:number;error?:string;blob?:Blob;outputName?:string};
const accepted=["pdf","docx","doc","xlsx","xls","csv","epub","mobi","png","jpg","jpeg","tif","tiff","djvu","zip","tar","tgz"];
const binderUrl=process.env.NEXT_PUBLIC_MDFY_BINDER_URL||"https://mybinder.org/v2/gh/fdossi/mdfy-runtime/main?urlpath=voila%2Frender%2Fvoila%2Fmdfy.ipynb";
const colabUrl=process.env.NEXT_PUBLIC_MDFY_COLAB_URL||"https://colab.research.google.com/github/fdossi/mdfy-runtime/blob/main/colab/MDfy_Colab.ipynb";
const ext=(name:string)=>name.toLowerCase().split(".").pop()||"";
const size=(value:number)=>value<1024?`${value} B`:value<1048576?`${(value/1024).toFixed(1)} KB`:`${(value/1048576).toFixed(1)} MB`;
export default function Home(){
 const input=useRef<HTMLInputElement>(null);const[items,setItems]=useState<Item[]>([]);const[drag,setDrag]=useState(false);const[busy,setBusy]=useState(false);const[zipping,setZipping]=useState(false);const[notice,setNotice]=useState("");
 const add=useCallback((files:File[])=>{const valid:Item[]=[];const bad:string[]=[];files.forEach(file=>{if(!accepted.includes(ext(file.name)))bad.push(file.name);else if(file.size>100*1024*1024)bad.push(`${file.name} (>100 MB)`);else valid.push({id:`${file.name}-${file.size}-${file.lastModified}`,file,state:"ready",progress:0})});setItems(old=>[...old,...valid.filter(next=>!old.some(current=>current.id===next.id))]);setNotice(bad.length?`Não foi possível adicionar: ${bad.join(", ")}.`:"")},[]);
 const choose=(event:ChangeEvent<HTMLInputElement>)=>{add(Array.from(event.target.files||[]));event.target.value=""};
 const drop=(event:DragEvent<HTMLDivElement>)=>{event.preventDefault();setDrag(false);add(Array.from(event.dataTransfer.files))};
 const convert=async()=>{setBusy(true);setNotice("");for(const item of items.filter(value=>value.state==="ready"||value.state==="error")){if(!LOCAL_FORMATS.has(ext(item.file.name))){setItems(all=>all.map(value=>value.id===item.id?{...value,state:"advanced",progress:0,error:undefined}:value));continue}setItems(all=>all.map(value=>value.id===item.id?{...value,state:"converting",progress:35,error:undefined}:value));try{const blob=await convertLocally(item.file);setItems(all=>all.map(value=>value.id===item.id?{...value,state:"done",progress:100,blob,outputName:`${item.file.name.replace(/\.[^.]+$/,'')}.md`}:value))}catch(error){setItems(all=>all.map(value=>value.id===item.id?{...value,state:"advanced",progress:0,error:error instanceof Error?error.message:"Este arquivo requer o conversor avançado."}:value))}}setBusy(false)};
 const download=(item:Item)=>{if(!item.blob)return;const anchor=document.createElement("a");anchor.href=URL.createObjectURL(item.blob);anchor.download=item.outputName||"arquivo.md";anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),1000)};
 const downloadAll=async()=>{const converted=items.filter((item):item is Item&{blob:Blob}=>item.state==="done"&&Boolean(item.blob));if(!converted.length)return;setZipping(true);setNotice("");try{const archive=new JSZip();const used=new Set<string>();const unique=(raw:string)=>{const safe=raw.replace(/^[/\\]+/,"").replace(/[<>:\"|?*]/g,"-")||"arquivo.md";if(!used.has(safe)){used.add(safe);return safe}const dot=safe.lastIndexOf(".");const stem=dot>0?safe.slice(0,dot):safe;const suffix=dot>0?safe.slice(dot):"";let n=2;while(used.has(`${stem}-${n}${suffix}`))n+=1;const name=`${stem}-${n}${suffix}`;used.add(name);return name};for(const item of converted)archive.file(unique(item.outputName||`${item.file.name.replace(/\.[^.]+$/,'')}.md`),item.blob);const blob=await archive.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}});const anchor=document.createElement("a");anchor.href=URL.createObjectURL(blob);anchor.download=`mdfy-markdown-${new Date().toISOString().slice(0,10)}.zip`;anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),1000)}catch(error){setNotice(error instanceof Error?`Não foi possível criar o ZIP: ${error.message}`:"Não foi possível criar o ZIP.")}finally{setZipping(false)}};
 const completed=useMemo(()=>items.filter(value=>value.state==="done"),[items]);const pending=useMemo(()=>items.filter(value=>value.state!=="done"),[items]);const done=completed.length;const advanced=useMemo(()=>items.filter(value=>value.state==="advanced").length,[items]);
 return <main><header className="topbar"><a className="brand" href="#inicio"><span className="brandMark">M↓</span><span>MDfy</span></a><nav><a href="#formatos">Formatos</a><a href="#como-funciona">Como funciona</a><a href="#privacidade">Privacidade</a></nav><a className="githubLink" href="https://github.com/fdossi/MDfy" target="_blank" rel="noreferrer">GitHub ↗</a></header>
 <section className="hero" id="inicio"><div className="eyebrow"><i/> Gratuito · privado · sem cadastro</div><h1>Converta arquivos para <em>Markdown.</em></h1><p className="heroText">Envie, converta e baixe em poucos segundos.</p>
 <div className="converterShell"><div className="converterCard"><div className={`dropZone ${drag?"dragging":""}`} onDragOver={event=>{event.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop} onClick={()=>input.current?.click()} role="button" tabIndex={0} onKeyDown={event=>{if(event.key==="Enter"||event.key===" ")input.current?.click()}}><input ref={input} type="file" multiple accept={accepted.map(value=>`.${value}`).join(",")} onChange={choose} hidden/><div className="uploadIcon">↑</div><div className="dropCopy"><h2>Arraste os arquivos aqui</h2><p>ou <button type="button" onClick={event=>{event.stopPropagation();input.current?.click()}}>selecione no dispositivo</button></p><span>Até 100 MB por arquivo</span></div></div>
 {notice&&<div className="notice" role="alert">{notice}</div>}{items.length>0&&<div className="fileList"><div className="listHeader"><strong>{pending.length} {pending.length===1?"arquivo na fila":"arquivos na fila"}</strong><button onClick={()=>setItems([])} disabled={busy||zipping}>Limpar tudo</button></div>{pending.map(item=><article className="fileRow" key={item.id}><div className="fileBadge">{ext(item.file.name).slice(0,4).toUpperCase()}</div><div className="fileMeta"><strong>{item.file.name}</strong><span>{size(item.file.size)} · {item.state==="ready"?(LOCAL_FORMATS.has(ext(item.file.name))?"Conversão local e privada":"Conversão avançada"):item.state==="converting"?"Convertendo no navegador…":item.state==="advanced"?(item.error||"Pronto para o ambiente avançado"):item.error}</span>{item.state==="converting"&&<div className="progress"><i style={{width:`${item.progress}%`}}/></div>}</div><button className="removeBtn" aria-label={`Remover ${item.file.name}`} onClick={()=>setItems(all=>all.filter(value=>value.id!==item.id))} disabled={busy}>×</button></article>)}{done+advanced<items.length&&<button className="convertButton" onClick={convert} disabled={busy}>{busy?"Convertendo arquivos…":done?"Converter restantes":"Converter para Markdown"}</button>}{advanced>0&&<div className="advancedPanel" role="status"><div><strong>{advanced} {advanced===1?"arquivo requer":"arquivos requerem"} conversão avançada</strong><p>O Binder abre o MDfy completo em um servidor temporário, sem login. O primeiro início pode levar alguns minutos.</p></div><div className="advancedActions"><a className="binderButton" href={binderUrl} target="_blank" rel="noreferrer">Abrir no Binder ↗</a><a className="colabButton" href={colabUrl} target="_blank" rel="noreferrer">Binder indisponível? Usar Colab ↗</a></div></div>}</div>}</div><aside className="resultsPanel" aria-live="polite"><div className="resultsHeader"><div><span>RESULTADOS</span><h2>Arquivos convertidos</h2></div><b>{done}</b></div>{done===0?<div className="resultsEmpty"><i>✓</i><strong>Seus arquivos aparecerão aqui</strong><p>Após a conversão, baixe cada Markdown ou reúna todos em um ZIP.</p></div>:<><div className="completedList">{completed.map(item=><article className="completedFile" key={item.id}><div className="mdBadge">MD</div><div><strong>{item.outputName||"arquivo.md"}</strong><span>{size(item.blob?.size||0)} · Concluído</span></div><button className="downloadIcon" onClick={()=>download(item)} aria-label={`Baixar ${item.outputName||item.file.name}`} title="Baixar arquivo">↓</button></article>)}</div><button className="zipButton" onClick={downloadAll} disabled={busy||zipping}>{zipping?"Criando arquivo ZIP…":`Baixar todos em ZIP (${done})`}</button></>}</aside></div><p className="trust"><span>✓</span> Processamento local quando possível <span>✓</span> Sem cadastro no Binder <span>✓</span> Download imediato</p></section>
 <section className="formats section" id="formatos"><Intro over="FORMATOS COMPATÍVEIS" title="A rota mais simples para cada arquivo." text="O MDfy escolhe automaticamente entre conversão local e o ambiente avançado."/><div className="formatGrid">{[["Documentos","PDF · DOCX local | DOC avançado","▤"],["Planilhas","XLSX · CSV local | XLS avançado","▦"],["E-books","EPUB local | MOBI avançado","▥"],["Imagens","PNG · JPG · TIFF com OCR avançado","▧"],["Digitalizados","PDF digitalizado · DJVU avançado","◫"],["Pacotes","ZIP · TAR · TGZ avançado","◇"]].map(value=><article key={value[0]}><b>{value[2]}</b><div><h3>{value[0]}</h3><p>{value[1]}</p></div></article>)}</div></section>
 <section className="steps section" id="como-funciona"><Intro over="COMO FUNCIONA" title="Privacidade primeiro, servidor apenas quando necessário."/><div className="stepGrid">{[["01","Envie","O MDfy identifica o formato sem transmitir o arquivo."],["02","Converta","PDF, DOCX, XLSX, CSV e EPUB permanecem no navegador."],["03","Avançado","Binder processa os demais; Colab fica disponível como contingência."]].map(value=><article key={value[0]}><span>{value[0]}</span><h3>{value[1]}</h3><p>{value[2]}</p></article>)}</div></section>
 <section className="privacy section" id="privacidade"><div><span>PRIVACIDADE POR PADRÃO</span><h2>O navegador é a primeira opção.</h2><p>Na conversão local, o arquivo não sai do dispositivo. Ao escolher o modo avançado, o documento é enviado diretamente ao ambiente temporário Binder ou Colab e deve ser baixado antes que a sessão termine.</p></div><div className="shield">✓</div></section><footer><a className="brand" href="#inicio"><span className="brandMark">M↓</span><span>MDfy</span></a><p>Conversão de arquivos para Markdown, sem complicação.</p><span>Projeto de código aberto · 2026</span></footer></main>}
function Intro({over,title,text}:{over:string;title:string;text?:string}){return <div className="sectionIntro"><span>{over}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
